services:
  mysql:
    image: mysql:8.0
    container_name: #{container_name}
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: #{db_password}
      MYSQL_DATABASE: #{db_name}
      MYSQL_USER: #{db_name}
      MYSQL_PASSWORD: #{db_password}
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data: